CREATE TABLE IF NOT EXISTS "user"
(
    id         				BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     			    VARCHAR(500) UNIQUE NOT NULL,
    date_of_birth     	    DATE,
    password     	        VARCHAR(500),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS account
(
    id         				BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     			BIGINT UNIQUE NOT NULL REFERENCES "user"(id),
    balance     	        DECIMAL NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);